// import { Character } from '../../../types/types';

// export const PLAYER_CHARACTERS: { [key: string]: any } = {
//   'Alerion Sturmfaust': {
//     name: 'Alerion Sturmfaust',
//     race: 'Elf',
//     class: 'Krieger',
//     level: 3,
//     background: 'Soldat',
//     alignment: 'Rechtschaffen Neutral',
//     stats: {
//       strength: 16,
//       dexterity: 14,
//       constitution: 14,
//       intelligence: 10,
//       wisdom: 12,
//       charisma: 8,
//     },
//     hp: {
//       max: 28,
//       current: 28,
//     },
//     ac: 17,
//     speed: 30,
//     proficiencies: {
//       armor: ['Leichte Rüstung', 'Mittlere Rüstung', 'Schwere Rüstung'],
//       weapons: ['Langschwert', 'Kurzbogen', 'Schild'],
//       tools: ['Schmiedewerkzeuge'],
//       languages: ['Gemeinsprache', 'Elfisch'],
//     },
//     savingThrows: ['Stärke', 'Konstitution'],
//     skills: {
//       athletics: 5,
//       intimidation: 2,
//       survival: 3,
//       perception: 3,
//     },
//     equipment: {
//       weapons: ['Langschwert', 'Schild'],
//       armor: ['Kettenhemd'],
//       gear: ['Rucksack', 'Abenteurerausrüstung', 'Schmiedewerkzeuge'],
//     },
//     features: ['Kampfstil: Verteidigung', 'Zweite Wind', 'Aktion Surge'],
//     languages: ['Gemeinsprache', 'Elfisch'],
//     player_name: 'Simon',
//   },
//   'Seraphina Lichthüter': {
//     name: 'Seraphina Lichthüter',
//     race: 'Mensch',
//     class: 'Kleriker',
//     level: 5,
//     background: 'Akolytin',
//     alignment: 'Neutral Gut',
//     stats: {
//       strength: 10,
//       dexterity: 12,
//       constitution: 14,
//       intelligence: 12,
//       wisdom: 18,
//       charisma: 14,
//     },
//     hp: {
//       max: 38,
//       current: 38,
//     },
//     ac: 16,
//     speed: 30,
//     proficiencies: {
//       armor: ['Leichte Rüstung', 'Mittlere Rüstung', 'Schwere Rüstung'],
//       weapons: ['Keule', 'Kriegshammer'],
//       tools: [],
//       languages: ['Gemeinsprache', 'Celestial'],
//     },
//     savingThrows: ['Weisheit', 'Charisma'],
//     skills: {
//       medicine: 7,
//       insight: 8,
//       religion: 4,
//       persuasion: 5,
//     },
//     equipment: {
//       weapons: ['Kriegshammer'],
//       armor: ['Schuppenpanzer'],
//       gear: ['Heiliges Symbol', 'Gebetsbuch', 'Heiltränke'],
//     },
//     spellcasting: {
//       0: {
//         spells: ['Licht', 'Widerstand'],
//         max: -1,
//         current: -1,
//       },
//       1: {
//         spells: ['Heilendes Wort', 'Segnen'],
//         max: 4,
//         current: 4,
//       },
//       2: {
//         spells: ['Lesser Restoration', 'Flammenschlag'],
//         max: 3,
//         current: 3,
//       },
//       3: {
//         spells: ['Daylight', 'Spirit Guardians'],
//         max: 2,
//         current: 2,
//       },
//     },
//     features: ['Göttliche Domäne: Licht', 'Channel Divinity'],
//     languages: ['Gemeinsprache', 'Celestial'],
//     player_name: 'Simon',
//   },
//   'Valen Schattenklinge': {
//     name: 'Valen Schattenklinge',
//     race: 'Halb-Elf',
//     class: 'Schurke',
//     level: 4,
//     background: 'Dieb',
//     alignment: 'Chaotisch Neutral',
//     stats: undefined,
//     // {
//     //   strength: 10,
//     //   dexterity: 18,
//     //   constitution: 12,
//     //   intelligence: 14,
//     //   wisdom: 10,
//     //   charisma: 16,
//     // },
//     hp: {
//       max: 24,
//       current: 24,
//     },
//     ac: 15,
//     speed: 30,
//     proficiencies: {
//       armor: ['Leichte Rüstung'],
//       weapons: ['Dolche', 'Kurzschwerter', 'Armbrust'],
//       tools: ['Diebeswerkzeuge'],
//       languages: ['Gemeinsprache', 'Untergemein'],
//     },
//     savingThrows: ['Geschicklichkeit', 'Intelligenz'],
//     skills: {
//       stealth: 7,
//       acrobatics: 6,
//       deception: 5,
//       investigation: 4,
//     },
//     equipment: {
//       weapons: ['Kurzschwert', 'Dolch'],
//       armor: ['Lederrüstung'],
//       gear: ['Diebeswerkzeuge', 'Schleuder', 'Rauchbomben'],
//     },
//     spellcasting: {},
//     features: ['Sneak Attack', 'Cunning Action'],
//     languages: ['Gemeinsprache', 'Untergemein'],
//     player_name: 'Simon',
//   },
// };
